### ISSUE TITLE
[Early Version] Issue Thread

### ISSUE THREAD

**Issue by Irohaede** [sspanel-uim/TrojanX#2]
Please post your idea about the early version here. DO NOT open any other issue.

**Comment by Irohaede** [comment]
# [Feature] SSPanel Node Speed Limit Overdrive

## How to implement

- [ ] Node API returning overdrived speed limit.
- [ ] Additional API request

**Comment by Irohaede** [comment]
# [Issue] Node specified traffic ratio is always 1.0

## Solution

A new Node API based on gRPC. (working)

**Comment by Irohaede** [comment]
# [Issue] Old passwords stay valid while they have changed

**Comment by jipeng521** [comment]
[trojan_x::sspanel::client] failed to fetch user: error decoding response body: expected value at line 1 column 1
 [reqwest::async_impl::client] response '404 Not Found'

**Comment by Irohaede** [comment]
@jipeng521 Please check `base_url` in your config.json.

**Comment by Irohaede** [comment]
# [Issue] UDP session high cpu usage & ineffective speed limit
Fix later. Please DO NOT use version 0.0.4.
