### ISSUE TITLE
绑定了 `cloudflare` 节点是正常注册,但是无法通过面板的配置代理成功

### ISSUE THREAD

**Issue by fupengl** [sspanel-uim/TrojanX#5]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/20211964/230142492-9be5f669-02a2-4995-8d4d-05d32657b238.png">

请教下是啥原因

**Comment by fupengl** [comment]
节点可以正常注册,显示在线状态, 获取到的订阅配置也是无法访问
<img width="499" alt="image" src="https://user-images.githubusercontent.com/20211964/230343988-6790aa16-7550-4d14-bbb3-8a4785d81389.png">
是什么配置有问题吗

**Comment by Irohaede** [comment]
The information you provided is not enough to identify the problem.
Please change the log level to `debug` and check its output.
BTW, I noticed you left your client SNI configuration with an empty string. Generally, you have to match the SNI between the client and server.

**Comment by fupengl** [comment]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/20211964/230387726-ca48b399-3998-488f-ade4-c9a18400c408.png">

**Comment by fupengl** [comment]
Boot log.
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/20211964/230390505-618c5d4d-5186-4300-b6e0-6b2c360a0c74.png">
